name: Notify on Phrase Translations Merge

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  notify-phrase-translations-merge:
    if: github.event.pull_request.merged == true && github.head_ref == 'phrase-translations'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get-branch-name
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Print branch name
        run: echo "Current branch is ${{ steps.get-branch-name.outputs.branch }}"

      - name: Post to Slack channel
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_PHRASE_CHANNEL_ID }}
          slack-message: "<!here> The `phrase-translations` branch has been merged into the `${{ steps.get-branch-name.outputs.branch }}` branch."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_PHRASE_TOKEN }}
